name: Model CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'model/**'
      - 'app.py'
      - 'quantize.py'
      - 'train_tokenizer.py'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  REPO_ID: "startprooo/sheikh-1B-instruct"

jobs:
  model-cicd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        precision:
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Run Model CI/CD Action
        uses: ./.github/actions/model-cicd-action
        with:
          python-version: '3.10'
          hf-token: ${{ secrets.HF_TOKEN }}
          repo-id: ${{ env.REPO_ID }}
          precision: ${{ matrix.precision }}
          run-test: 'true'
          run-quantization: 'true'
          run-upload: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}